name: "Release dev container features & Generate Documentation"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-workflow-test:
    uses: "./.github/workflows/test.yaml"

  deploy:
    needs: [call-workflow-test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}